---
title: Data generation
output: github_document
---

```{r}
library("tibble")
library("tidyr")
library("readr")
library("dplyr")
library("here")
```
## Bar Charts

```{r}
n_obs <- 10

get_data <- function(){
  tibble(
    category = LETTERS[seq(n_obs)],
    number = round(rnorm(n_obs, 100, 50))
  )  
}
```

```{r}
data_01 <- get_data()
data_02 <- get_data()
```

```{r}
data_01
data_02
```

```{r}
write_csv(data_01, here("data-raw", "data_01.csv"))
write_csv(data_02, here("data-raw", "data_02.csv"))
```

## Labeling

```{r}
make_circle <- function(n_obs = 50, radius = 1, jitter = 0.01) {
  
  z = (seq(n_obs) - 1) / n_obs
  
  theta <- 2 * pi * z
  
  tibble(
    index = seq(n_obs),
    x = radius * cos(theta) + rnorm(n_obs, 0, jitter),
    y = radius * sin(theta) + rnorm(n_obs, 0, jitter),
  )
}
```

```{r}
make_rectangle <- function(n_obs = 50, dx = 1, dy = 1, jitter = 0.01) {
  
  z = (seq(n_obs) - 1) / n_obs
    
  tibble(
    index = seq(n_obs),
    x = 
      case_when(
        z < 0.25 ~ dx,
        z < 0.50 ~ dx - 8 * dx * (z - 0.25), 
        z < 0.75 ~ -dx,
        TRUE ~ -dx + 8 * dx * (z - 0.75)
      ) + 
      rnorm(n_obs, 0, jitter),
    y = 
      case_when(
        z < 0.25 ~ -dy + 8 * dy * z,
        z < 0.50 ~ dy, 
        z < 0.75 ~ dy - 8 * dy * (z - 0.50),
        TRUE ~ -dy
      ) + 
      rnorm(n_obs, 0, jitter),    
  )
  
  
}
```

```{r}
data <- make_rectangle(dx = 1, dy = 0.5)
```

```{r}
chart <- 
  alt$Chart(data = r_to_py(data))$
  mark_line()$
  encode(
    x = alt$X("x:Q", scale = alt$Scale(domain = list(-1.2, 1.2))),
    y = alt$Y("y:Q", scale = alt$Scale(domain = list(-1.2, 1.2))),
    order= "index:Q"
  )

chart$
  properties(width = 400, height = 400)
```